architecture:
    output_channels : 2
    input_shape : [256,256, 1]
    a_test_argument_1: 'None'
    a_test_argument_2: 'None'

metrics:
    train_metric_name: dice

controller:
    controller_host : 'd7920-12.ccds.io'                                                  # required
    controller_port : 27024                                                               # required
    controller_database : 'test_databases'                                                # required
    controller_collection: 'test_design'                                                  # required
    controller_ssl_certfile: './pki/client.pem'                                           # required
    controller_ssl_ca_file: './pki/rootCA.pem'                                            # required
    num_warm_up: 10                                                                       # required
    max_iter: 75                                                                          # required
    max_local_iter: 5 # required
    
manager:
    manager_host : 'd7920-12.ccds.io'                                                  # required
    manager_port : 27024                                                               # required
    manager_database : 'test_databases'                                                # required
    manager_collection: 'test_trial'                                                   # required
    manager_ssl_certfile: './pki/client.pem'                                           # required
    manager_ssl_ca_file: './pki/rootCA.pem'                                            # required
    start_recording: 5

hyperparameters:
    param_1:
        name: 'learning_rate'
        type: 'discrete'
        domain: (0.005, 0.001)
        
    param_3:
        name: 'num_convs'
        type: 'discrete'
        domain: (1, 2)

    param_4:
        name: 'network'
        type: 'discrete'
        domain: (0,1,2,3,4)

    param_5:
        name: 'dropout'
        type: 'discrete'
        domain: (0, 0.1, 0.2)

    param_6:
        name: 'kernel'
        type: 'discrete'
        domain: (3, 5)
    
    param_8:
        name: 'normalize'
        type: 'discrete'
        domain: (0, 1)
        
    param_9:
        name: 'vertical_flip'
        type: 'discrete'
        domain: (0, 1)